- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> [#8] setup issue templates

- l10n.yaml
> [#13]: `Fix wrong configuration`

- l10n.yaml
> [#13]: Bugfix/gh 13 wrong l10n

- .github/workflows/check.yml
> [#9]: `implemented github action`

- lib/src/core/localization/app_localization.dart
- lib/src/core/widget/app_context.dart
- pubspec.yaml
> [#24]: `Setup l10n helper and codegen`

- lib/src/core/router/routes.dart
- lib/src/core/widget/app_context.dart
- lib/src/feature/initialization/logic/initialization_steps.dart
- lib/src/feature/initialization/model/initialization_progress.dart
- pubspec.yaml
> [#19]: `Setup GoRouter`

- .gitignore
- build.yaml
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/src/core/router/routes.dart
- lib/src/core/theme/app_colors.dart
- lib/src/core/theme/theme.dart
- lib/src/core/widget/app_context.dart
- pubspec.yaml
> [#35]: `Setup theming and coloring`

- .github/workflows/check.yml
- analysis_options.yaml
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> [#22]: `Setup beautiful pubspec`

- lib/src/feature/app/logic/app_runner.dart
- lib/src/feature/initialization/logic/initialization_processor.dart
Rename to processInitialization
> [hotfix]: `Rename process method`

- lib/src/feature/app/logic/app_runner.dart
> [#85]: documented app_runner

- .github/workflows/check.yml
- lib/runner_shared.dart
- lib/src/core/data/rest_client.dart
- test/unit/rest_client/rest_client_test.dart
> Test build request

- lib/src/core/data/rest_client.dart
- test/unit/rest_client/rest_client_test.dart
> Written tests for test_decode_response

- test/unit/rest_client/rest_client_test.dart
> Tested RestClient.encodeBody

- test/unit/rest_client/rest_client_test.dart
> Added tests for GET and POST

- README.md
Added anchor to initialization `how to add a new dependency`
> Added anchor to initialization how to

- pubspec.yaml
Reverts sizzleco/sizzle_starter#153
> Revert "Bump flutter_native_splash, flutter_launcher_icons, auto_route_generator and auto_route"

- build.yaml
- pubspec.yaml
- bumped version in pubspec.yaml
- fixed build.yaml (removed tailor)
> Bumped auto_route version

- .gitignore
- lib/runner_shared.dart
- lib/src/core/utils/logger.dart
- lib/src/feature/app/logic/app_runner.dart
- pubspec.yaml
- added platform dispatcher on error handling
- added flutter_gen
> Some improvements

- lib/src/core/bloc/observer.dart
- lib/src/core/utils/extensions/string_extension.dart
- lib/src/core/utils/logger.dart
- lib/src/feature/app/logic/app_runner.dart
- pubspec.yaml
- Added sequential transformer
- Implemented BlocObserver
fixes #168 #169
> Bloc features

- lib/src/core/database/app_database.dart
- lib/src/core/database/connection/open_connection_html.dart
- lib/src/core/database/connection/open_connection_io.dart
- lib/src/core/database/connection/open_connection_stub.dart
> Implemented Drift connection & database

- lib/src/core/utils/logger.dart
> Refactor LogFormatter

- .github/workflows/code-analysis.yml
- build.yaml
- lib/src/core/utils/extensions/context_extension.dart
- lib/src/feature/app/logic/locale_bloc.dart
- lib/src/feature/app/logic/theme_bloc.dart
- lib/src/feature/app/widget/locale_scope.dart
- lib/src/feature/app/widget/theme_scope.dart
- pubspec.yaml
- Refactored locale
- Added build.yaml
> Added freezed & Refactored

- lib/src/feature/app/logic/tracking_manager.dart
Sentry show more env information in issue when use SentryFlutter.init
> Use SentryFlutter.init instead of Sentry.init

- lib/main.dart
- lib/src/core/localization/localization.dart
- lib/src/core/utils/app_bloc_observer.dart
- lib/src/core/utils/logger.dart
- lib/src/feature/app/logic/app_runner.dart
- lib/src/feature/app/logic/tracking_manager.dart
- lib/src/feature/initialization/logic/initialization_factory.dart
- lib/src/feature/initialization/logic/initialization_processor.dart
- lib/src/feature/initialization/model/environment.dart
- lib/src/feature/initialization/model/environment_store.dart
Enhances error tracking and sending to Sentry.
Closes #284
> Improved error tracking (#284)

- lib/src/core/rest_client/src/http/rest_client_http.dart
- lib/src/feature/app/logic/app_runner.dart
- pubspec.yaml
> Added CronetClient and CupertinoClient

- core/common/lib/src/persisted_column/shared_preferences_column.dart
- feature/settings/lib/src/data/datasources/settings_local_datasource.dart
Use SharedPreferencesColumnJson to save settings as JSON.
> refactor(settings): use SharedPreferencesColumnJson
